### PR TITLE
Fix for issue #2224

### LINKED ISSUE #2224: Graph feature on Containerlab not showing interface tags correctly
**Issue:-** Graph feature on Containerlab displaying incorrect interface IDs. 

containerlab version:- 

```
sudo clab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.57.5
     commit: fbca124e
       date: 2024-09-30T10:53:07Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.57/#0575

```
**Topology YAML** 

```
name: eos_mlag

topology:
  nodes:
    ceos1:
      kind: ceos
      image: ceos:4.32.0F
      startup-config: ceos1.cfg 
    ceos2:
      kind: ceos
      image: ceos:4.32.0F
      startup-config: ceos2.cfg
  links:
    - endpoints: ["ceos1:eth47", "ceos2:eth47"]
    - endpoints: ["ceos1:eth48", "ceos2:eth48"]

```

**LLDP output from COES1 & CEOS2**

```
ceos1#show lldp nei 
Last table change time   : 0:19:11 ago
Number of table inserts  : 3
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et47          ceos2                    Ethernet47          120
Et48          ceos2                    Ethernet48          120
Ma0           ceos2                    Management0         120

ceos2#show lldp nei 
Last table change time   : 0:19:21 ago
Number of table inserts  : 3
Number of table deletes  : 0
Number of table drops    : 0
Number of table age-outs : 0

Port          Neighbor Device ID       Neighbor Port ID    TTL
---------- ------------------------ ---------------------- ---
Et47          ceos1                    Ethernet47          120
Et48          ceos1                    Ethernet48          120
Ma0           ceos1                    Management0         120

```

**Graph Topology** 

Screenshot from 2024-10-07 17-36-35

### PR DESCRIPTION
**Pull request by jkary**
This request contains a fix for the GitHub issue 2224. The fix focuses on the separation of labels for multiple links between the same two nodes. There appears to be the following other issues:

1) Popup labels for a link don't appear in the right place and sometimes shows the wrong link.
2) Horizontal and vertical layouts appear to have the opposite effect.

As this is my first commit, please help me understand if I am doing something wrong.

Jason

fix #2224

### CODE REVIEW

**Comment by hellt** [comment]
had a comment about the way it works in our discord: https://discord.com/channels/860500297297821756/1308463195047858217

File: clab/graph_templates/nextui/static/js/script.js [hunk 1]
```diff
@@ -89,8 +89,31 @@
             'setModel': function (model) {
                 this.inherited(model);
             },
+            calculateLabelPosition: function(percentDistance) {
+              var l = this.line();
+              var n = this.line().normal().multiply(this.getOffset()*3);
```
Comment (hellt) [inline clab/graph_templates/nextui/static/js/script.js:94]: what happened here: 26,455 additions

Comment (jkary) [reply clab/graph_templates/nextui/static/js/script.js:94]: I also updated the next.js script to make it the non-minified version.  I think it will be easier to maintain in the future for the limited future it has left.  I had to update the next.js to use the positionAlongCurve method.  I'm happy to change back to the minified version if you want, but the framework no longer being worked on and seems easier for the next person.
