### PR TITLE
cmd/destroy: Fix tools containers not being removed when using --all

### LINKED ISSUE #2637: Destroying with `--all` and `--cleanup` does not remove the sshx container
Deploy a lab and attach the sshx container:

```
clab dep -c -t srlinux.dev/clab-srl2
```

```
clab tools sshx attach -l srl2
```

Now try redeploying the lab:

```
dclab dep -c -t srlinux.dev/clab-srl2
```

The non-removed sshx container prevents the lab from being deployed again:

```
12:43:20 INFO Containerlab started version=0.0.0
12:43:20 INFO Parsing & checking topology file=topo-3442689307.clab.yml
12:43:20 INFO Destroying lab name=srl2
12:43:21 INFO Removed container name=srl1
12:43:21 INFO Removed container name=srl2
12:43:21 INFO Removing host entries path=/etc/hosts
12:43:21 INFO Removing SSH config path=/etc/ssh/ssh_config.d/clab-srl2.conf
12:43:21 INFO Removing directory path=/tmp/.clab/clab-srl2
          
   ERROR  
          
  The 'srl2' lab has already been deployed. Destroy the lab before deploying a lab with the same name.                

  Try --help for usage.
```

### PR DESCRIPTION
**Pull request by vista-**
This PR fixes #2637 by removing the !all condition from the tool container removal part of destroy.

### CODE REVIEW

File: cmd/destroy.go [hunk 1]
```diff
@@ -194,24 +194,28 @@ func destroyFn(_ *cobra.Command, _ []string) error {
 	}
 
 	// Remove any tool containers associated with destroyed labs
-	if !all && len(labs) > 0 {
-		// Get the lab name from the first lab
-		labName := labs[0].Config.Name
-		log.Debugf("Looking for tool containers with lab name: %s", labName)
-
-		// Initialize runtime
+	if len(labs) > 0 {
```
Comment (hellt) [inline cmd/destroy.go]: @vista- I think this does not address the linked issue...

```
dclab dep -c -t srlinux.dev/clab-srl2
15:54:22 INFO Containerlab started version=0.0.0
15:54:22 INFO Parsing & checking topology file=topo-1646392938.clab.yml
15:54:22 INFO Destroying lab name=srl2
15:54:22 INFO Removed container name=srl1
15:54:22 INFO Removed container name=srl2
15:54:22 INFO Removing host entries path=/etc/hosts
15:54:22 INFO Removing SSH config path=/etc/ssh/ssh_config.d/clab-srl2.conf
15:54:22 INFO Removing directory path=/tmp/.clab/clab-srl2
          
   ERROR  
          
  The 'srl2' lab has already been deployed. Destroy the lab before deploying a lab with the same name.                

  Try --help for usage.
```

**Review by hellt — CHANGES_REQUESTED** [review]

File: cmd/destroy.go (hunk 1 above)
Comment (vista-) [reply cmd/destroy.go]: I think this is fixed now!
