### PR TITLE
Node filtering

### LINKED ISSUE #1295: FR: Add flag to deploy subset of nodes from topology
When deploying on GitHub CI/CD, resources are limited and deployment of a full 3-layer CLOS topology with 16 nodes - representing a digital twin of a real deployment - fails.

For testing purposes, I'd like to be able to select a representative subset ( say leaf1, leaf2, spine1, host1, host2 ) to validate the topology, without maintaining 2 separate topology files

Using Netlab I can do '--limit leaf1,leaf2,...' and it will work as expected, an optional deploy flag with a list of node names could do the same for Containerlab

### PR DESCRIPTION
**Pull request by steiler**
This is the continuation of #1296

fix #1295

### CODE REVIEW

File: clab/clab.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ import (
 	"github.com/srl-labs/containerlab/runtime/docker"
 	"github.com/srl-labs/containerlab/runtime/ignite"
 	"github.com/srl-labs/containerlab/types"
+	"k8s.io/utils/strings/slices"
```
Comment (hellt) [inline clab/clab.go:25]: our `internal/slices/slices.go` contains the `Contains` function already. No need for this import

**Comment by karimra** [comment]
It would be good to have the same functionality based on group and/or labels as well.

File: clab/clab.go (hunk 1 above)
Comment (steiler) [reply clab/clab.go]: migrated to utils.StringInSlice

**Comment by jbemmel** [comment]
> It would be good to have the same functionality based on group and/or labels as well.

You mean like --node-filter group:leaves

**Comment by karimra** [comment]
> > It would be good to have the same functionality based on group and/or labels as well.
> 
> You mean like `--node-filter group:leaves`? or `--node-filter label:ci-nodes`

yes but I would use the same syntax as docker `group=leaves`

File: clab/clab.go [hunk 2]
```diff
@@ -113,6 +114,69 @@ func WithTopoFile(file, varsFile string) ClabOption {
...
+		if containsAside && containsBside {
+			log.Debugf("Including link %+v", l)
+			newLinks = append(newLinks, l)
+		}
+	}
+	// replace the original collection of links with the links that have both endpoints in the node filter
+	c.Config.Topology.Links = newLinks
+
+	return nil
+}
```
Comment (hellt) [inline clab/clab.go:178]: Hi @steiler 
I changed this func a bit by removing the nested if and dealing with nodes map by deleting the elements from existing map. [ec0e1f9](https://github.com/srl-labs/containerlab/pull/1298/commits/ec0e1f99cd5f16da77e3e7d83f6ccd87963591f7)

I also carved out the function from the option func, so that we can unit test it and wrote a basic test.
